SctPkg: Fix missing function declaration error
Fix compilation error: implicit declaration of function
‘SctDevicePathStrFromProtocol’ [-Wimplicit-function-declaration].

Signed-off-by: Luigi Leonardi <leonardi@redhat.com>